In [2]:
#Install pandas

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Import pandas
import pandas as pd

In [5]:
pd.__version__

'3.0.0'

# Dataframe

In [6]:
 # 1. Create dataframe
df = pd.DataFrame([11,22,33], columns=['col_Name'])
print(df) # by default start by 0

   col_Name
0        11
1        22
2        33

In [7]:
print(type(df))

<class 'pandas.DataFrame'>

In [8]:
data = {
    
    'Name': ['madhav','vishakha','lalita','rishabh'],
    'Age' : [16,17,18,19],
    'Salary' : [6000,8000,9000,10000]
}

In [9]:
df = pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000
<class 'pandas.DataFrame'>

## More understanding on Dataframe

In [10]:
df.head() # print top rows

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000

In [11]:
df.head(2) # print 2 top rows

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000

In [12]:
df.tail()  # print bottom rows

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000

In [13]:
df.tail(3) # print bottom 3 rows

       Name  Age  Salary
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000

In [14]:
df.shape

(4, 3)

In [15]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [16]:
df.rename(columns={'Salary' :'Monthly_salary'}, inplace = True)  #changed in same dataframe

# or use df1 = df.rename(columns={'Salary' : 'Monthly_salary'})

In [17]:
df

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000
3   rishabh   19           10000

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [19]:
df.describe() # give statisistic summary about numerical type columns

             Age  Monthly_salary
count   4.000000        4.000000
mean   17.500000     8250.000000
std     1.290994     1707.825128
min    16.000000     6000.000000
25%    16.750000     7500.000000
50%    17.500000     8500.000000
75%    18.250000     9250.000000
max    19.000000    10000.000000

## SAVE AND LOAD DATA FROM CSV

In [ ]:
df.to_csv('Test_data.csv', index = False)   # here df = name of dataframe 
# export dataframe

In [ ]:
load_df = pd.read_csv('Test_data.csv') # function to load dataframe
#import dataframe
load_df                 # i incremented rishab's salary in excel

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000
3   rishabh   19           12000