In [87]:
#Install pandas

In [88]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [89]:
# Import pandas
import pandas as pd

In [90]:
pd.__version__

'3.0.0'

# Dataframe

In [91]:
 # 1. Create dataframe
df = pd.DataFrame([11,22,33], columns=['col_Name'])
print(df) # by default start by 0

   col_Name
0        11
1        22
2        33

In [92]:
print(type(df))

<class 'pandas.DataFrame'>

In [93]:
data = {
    
    'Name': ['madhav','vishakha','lalita','rishabh'],
    'Age' : [16,17,18,19],
    'Salary' : [6000,8000,9000,10000]
}

In [94]:
df = pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000
<class 'pandas.DataFrame'>

## More understanding on Dataframe

In [95]:
df.head() # print top rows

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000

In [96]:
df.head(2) # print 2 top rows

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000

In [97]:
df.tail()  # print bottom rows

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000

In [98]:
df.tail(3) # print bottom 3 rows

       Name  Age  Salary
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000

In [99]:
df.shape

(4, 3)

In [100]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [101]:
df.rename(columns={'Salary' :'Monthly_salary'}, inplace = True)  #changed in same dataframe

# or use df1 = df.rename(columns={'Salary' : 'Monthly_salary'})

In [102]:
df

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000
3   rishabh   19           10000

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [104]:
df.describe() # give statisistic summary about numerical type columns

             Age  Monthly_salary
count   4.000000        4.000000
mean   17.500000     8250.000000
std     1.290994     1707.825128
min    16.000000     6000.000000
25%    16.750000     7500.000000
50%    17.500000     8500.000000
75%    18.250000     9250.000000
max    19.000000    10000.000000

## SAVE AND LOAD DATA FROM CSV

In [105]:
df.to_csv('Test_data.csv', index = False)   # here df = name of dataframe 
# export dataframe

In [106]:
load_df = pd.read_csv('Test_data.csv') # function to load dataframe
#import dataframe
load_df                 # i incremented rishab's salary in excel

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000
3   rishabh   19           10000

# Rows and Columns Selection

In [107]:
df          # whole table of data

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000
3   rishabh   19           10000

In [108]:
# COLUMN SELECTION
df[['Name']]            # single column

       Name
0    madhav
1  vishakha
2    lalita
3   rishabh

In [109]:
df[['Name', 'Monthly_salary']]          # multi column

       Name  Monthly_salary
0    madhav            6000
1  vishakha            8000
2    lalita            9000
3   rishabh           10000

# Selecting row

In [110]:
# loc - index name based
df.loc[df.Name =='Madhav']
df.loc[(df.Name == 'Madhav') & (df.Monthly_salary>=5000)]

Empty DataFrame
Columns: [Name, Age, Monthly_salary]
Index: []

In [111]:
# iloc - index value based
df.iloc[0]     # gave me everything that was on index 0

Name              madhav
Age                   16
Monthly_salary      6000
Name: 0, dtype: object

In [112]:
df.iloc[0:2] # will work till (n-1)

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000

In [113]:
df.loc[0:2]   #  loc will include 2 as well

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000

# Filter Dataframe

In [114]:
df['Age'] > 15

0    True
1    True
2    True
3    True
Name: Age, dtype: bool

In [115]:
df['Age']>= 18

0    False
1    False
2     True
3     True
Name: Age, dtype: bool

In [116]:
df[df['Age'] >= 18]   # to filter out only true values

      Name  Age  Monthly_salary
2   lalita   18            9000
3  rishabh   19           10000

In [117]:
df_age_filter = df[df['Age'] >= 18]
df_age_filter

      Name  Age  Monthly_salary
2   lalita   18            9000
3  rishabh   19           10000

In [118]:
# filtering on the basis of 2 parameters
df[(df['Age'] >= 18) & (df['Monthly_salary'] >= 10000)]

      Name  Age  Monthly_salary
3  rishabh   19           10000

In [119]:
df.where(df['Age'] >= 18)     # keeps no. of rows and columns same

      Name   Age  Monthly_salary
0      NaN   NaN             NaN
1      NaN   NaN             NaN
2   lalita  18.0          9000.0
3  rishabh  19.0         10000.0

In [120]:
df.where(df['Age'] >= 18 , other = 'Not Eligible')

           Name           Age Monthly_salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        lalita            18           9000
3       rishabh            19          10000

## Operations On Rows And Columns( add , update, delete)

In [121]:
# Add new column
df['Team'] = ['CEO' , 'HR' , 'CTO' , 'DA']
df

       Name  Age  Monthly_salary Team
0    madhav   16            6000  CEO
1  vishakha   17            8000   HR
2    lalita   18            9000  CTO
3   rishabh   19           10000   DA

In [122]:
df['Bonus'] = df['Monthly_salary']*0.4
df       #performed operation and added new column

       Name  Age  Monthly_salary Team   Bonus
0    madhav   16            6000  CEO  2400.0
1  vishakha   17            8000   HR  3200.0
2    lalita   18            9000  CTO  3600.0
3   rishabh   19           10000   DA  4000.0

In [123]:
# Adding new row
df.loc[len(df)] =['sam' , 22 , 5500, ' EMPLOYEE' , 2000]  # this method will create a new row with this data as many times as you run this cell.
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17            8000         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

In [124]:
# deleting duplicates
df = df.drop_duplicates()
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17            8000         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

In [125]:
df = df.iloc[:5]
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17            8000         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

In [126]:
len(df)

5

# Update value

In [127]:
df.loc[1,'Monthly_salary'] = 9500
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17            9500         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

In [128]:
# Update value using column name

df.loc[df.Name == 'vishakha', 'Monthly_salary'] = 11000
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17           11000         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

#Deleting value - row and column values

In [129]:
df = df.drop(df[df.Name == 'lalita'].index)   # drops row by default if not specified
# 0 --> row   ,   1 --> column

In [130]:
df[df.Name == 'lalita']

Empty DataFrame
Columns: [Name, Age, Monthly_salary, Team, Bonus]
Index: []

In [131]:
df.drop(1,axis =0) # index name

      Name  Age  Monthly_salary       Team   Bonus
0   madhav   16            6000        CEO  2400.0
3  rishabh   19           10000         DA  4000.0
4      sam   22            5500   EMPLOYEE  2000.0

In [132]:
# Deleting column
df.drop('Bonus', axis =1, inplace= True)

In [133]:
df

       Name  Age  Monthly_salary       Team
0    madhav   16            6000        CEO
1  vishakha   17           11000         HR
3   rishabh   19           10000         DA
4       sam   22            5500   EMPLOYEE

In [134]:
#df =df.drop(['Age','Team'],axis = 1)   # deleting multiple column
df

       Name  Age  Monthly_salary       Team
0    madhav   16            6000        CEO
1  vishakha   17           11000         HR
3   rishabh   19           10000         DA
4       sam   22            5500   EMPLOYEE

In [135]:
df

       Name  Age  Monthly_salary       Team
0    madhav   16            6000        CEO
1  vishakha   17           11000         HR
3   rishabh   19           10000         DA
4       sam   22            5500   EMPLOYEE

## Sort Values

In [136]:
df.sort_values('Monthly_salary')   # ascending order by default

       Name  Age  Monthly_salary       Team
4       sam   22            5500   EMPLOYEE
0    madhav   16            6000        CEO
3   rishabh   19           10000         DA
1  vishakha   17           11000         HR

In [137]:
df.sort_values('Monthly_salary', ascending = False)   #descending order

       Name  Age  Monthly_salary       Team
1  vishakha   17           11000         HR
3   rishabh   19           10000         DA
0    madhav   16            6000        CEO
4       sam   22            5500   EMPLOYEE

## Working with date value

In [138]:
df['DOJ'] = ['2024-01-01','2024-01-15','2024-03-28','2024-03-03']
df

       Name  Age  Monthly_salary       Team         DOJ
0    madhav   16            6000        CEO  2024-01-01
1  vishakha   17           11000         HR  2024-01-15
3   rishabh   19           10000         DA  2024-03-28
4       sam   22            5500   EMPLOYEE  2024-03-03

In [139]:
df['DOJ'].dtype

In [140]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [141]:
df['DOJ'].dtype   # rep datatime64[ns] data type in pandas

dtype('<M8[us]')

In [142]:
df1 = df

In [143]:
df1['DOJ2'] = ['01-01-2025','15-01-2025','28-03-2025','03-03-2025']
df1

       Name  Age  Monthly_salary       Team        DOJ        DOJ2
0    madhav   16            6000        CEO 2024-01-01  01-01-2025
1  vishakha   17           11000         HR 2024-01-15  15-01-2025
3   rishabh   19           10000         DA 2024-03-28  28-03-2025
4       sam   22            5500   EMPLOYEE 2024-03-03  03-03-2025

In [144]:
df1['DOJ2'].dtype

In [145]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format ='%d-%m-%Y')
df1['DOJ2'].dtype

dtype('<M8[us]')

In [146]:
df = df.drop('DOJ2', axis = 1)
df

       Name  Age  Monthly_salary       Team        DOJ
0    madhav   16            6000        CEO 2024-01-01
1  vishakha   17           11000         HR 2024-01-15
3   rishabh   19           10000         DA 2024-03-28
4       sam   22            5500   EMPLOYEE 2024-03-03

In [147]:
   # Extract year, month, week ,day
df['DOJ'].dt.year

0    2024
1    2024
3    2024
4    2024
Name: DOJ, dtype: int32

In [148]:
df['DOJ'].dt.month

0    1
1    1
3    3
4    3
Name: DOJ, dtype: int32

In [149]:
df['DOJ'].dt.day_name()

0      Monday
1      Monday
3    Thursday
4      Sunday
Name: DOJ, dtype: str

In [150]:
df['month'] = df['DOJ'].dt.month
df   # saved the extracted month data into a new month column in df

       Name  Age  Monthly_salary       Team        DOJ  month
0    madhav   16            6000        CEO 2024-01-01      1
1  vishakha   17           11000         HR 2024-01-15      1
3   rishabh   19           10000         DA 2024-03-28      3
4       sam   22            5500   EMPLOYEE 2024-03-03      3

In [151]:
df['DOJ'] + pd.Timedelta(days = 90) # represents a duration , the difference between two dates or times.

0   2024-03-31
1   2024-04-14
3   2024-06-26
4   2024-06-01
Name: DOJ, dtype: datetime64[us]

## Handling missing values

In [152]:
df

       Name  Age  Monthly_salary       Team        DOJ  month
0    madhav   16            6000        CEO 2024-01-01      1
1  vishakha   17           11000         HR 2024-01-15      1
3   rishabh   19           10000         DA 2024-03-28      3
4       sam   22            5500   EMPLOYEE 2024-03-03      3

In [153]:
df.isnull() # give boolean value if null then true else false

    Name    Age  Monthly_salary   Team    DOJ  month
0  False  False           False  False  False  False
1  False  False           False  False  False  False
3  False  False           False  False  False  False
4  False  False           False  False  False  False

In [154]:
import numpy as np

In [155]:
df.loc[df.Name == 'rishabh','Monthly_salary'] = np.nan

In [156]:
df

       Name  Age  Monthly_salary       Team        DOJ  month
0    madhav   16          6000.0        CEO 2024-01-01      1
1  vishakha   17         11000.0         HR 2024-01-15      1
3   rishabh   19             NaN         DA 2024-03-28      3
4       sam   22          5500.0   EMPLOYEE 2024-03-03      3

In [157]:
df.isnull()     # you'll se true for monthly salary of rishabh

    Name    Age  Monthly_salary   Team    DOJ  month
0  False  False           False  False  False  False
1  False  False           False  False  False  False
3  False  False            True  False  False  False
4  False  False           False  False  False  False

In [158]:
# .null() wont work for huge data we'll use another method for that

df.isnull().sum()  # will give sum of null values

Name              0
Age               0
Monthly_salary    1
Team              0
DOJ               0
month             0
dtype: int64

In [159]:
df.fillna(8000,inplace=True)

       Name  Age  Monthly_salary       Team        DOJ  month
0    madhav   16          6000.0        CEO 2024-01-01      1
1  vishakha   17         11000.0         HR 2024-01-15      1
3   rishabh   19          8000.0         DA 2024-03-28      3
4       sam   22          5500.0   EMPLOYEE 2024-03-03      3

## Aggregation and group by

In [160]:
df['Team'].value_counts()  # will give the count of each team members

Team
CEO          1
HR           1
DA           1
 EMPLOYEE    1
Name: count, dtype: int64

In [161]:
df['month'].value_counts()    # gives frequency of value.

month
1    2
3    2
Name: count, dtype: int64

In [162]:
# what is i only want count of a specific thing like count of a specific month or team designation or specific monthly salary

In [163]:
df[df['month']==1].value_counts()   # will give count of only those employee's whose month is assigned 1.

Name      Age  Monthly_salary  Team  DOJ         month
madhav    16   6000.0          CEO   2024-01-01  1        1
vishakha  17   11000.0         HR    2024-01-15  1        1
Name: count, dtype: int64

In [164]:
df.groupby('month')['Monthly_salary'].sum() # will add the salary on the basis of month
# check montlhy salary made in my company.


# ON THE BASIS OF MONTH AGGREGATE MONTHLY SALARY

month
1    17000.0
3    13500.0
Name: Monthly_salary, dtype: float64

In [165]:
df.groupby('Monthly_salary')['month'].sum()  # ON THE BASIS OF MONTHLY SALARY AGGREGATE MONTH.

Monthly_salary
5500.0     3
6000.0     1
8000.0     3
11000.0    1
Name: month, dtype: int32

In [166]:
df

       Name  Age  Monthly_salary       Team        DOJ  month
0    madhav   16          6000.0        CEO 2024-01-01      1
1  vishakha   17         11000.0         HR 2024-01-15      1
3   rishabh   19          8000.0         DA 2024-03-28      3
4       sam   22          5500.0   EMPLOYEE 2024-03-03      3

In [167]:
df.groupby('month')['Monthly_salary'].mean()

month
1    8500.0
3    6750.0
Name: Monthly_salary, dtype: float64

     ---  Aggregation upon multiple columns  ---

In [168]:
df.groupby('month').agg({'Monthly_salary' : 'mean', 'Name' : 'count' })

       Monthly_salary  Name
month
1              8500.0     2
3              6750.0     2

### Concatenate and merge dataframe (JOINS)

In [169]:
df1 = pd.DataFrame({'ID': [1,2,3],'Name' : ['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [175]:
df2 = pd.DataFrame({'ID': [1,2,2,4],'Score' : [88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [176]:
pd.concat([df1,df2], axis =0)   # top on top / row level / vertical
# nulls the value that don't match

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [172]:
pd.concat([df1,df2], axis =1)   # side on side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   3     77
3  NaN  NaN   4     79

# MERGE

In [ ]:
# INNER (default)= Keeps only matching rows based on the join keys.
#Rows without a match in both DataFrames are dropped.

In [183]:
## OUTER = Keeps all rows from both DataFrames.
#Missing values are filled with NaN.

In [184]:
# LEFT = Keeps all rows from the left DataFrame.
#Adds matching rows from the right DataFrame; unmatched rows get NaN.

In [185]:
# RIGHT = Keeps all rows from the right DataFrame.
#Adds matching rows from the left DataFrame; unmatched rows get NaN.

In [ ]:
#merge = join
pd.merge(df1, df2 , how = 'inner', on = 'ID')

# SYNTAX=    (left: DataFrame | Series[Any], right: DataFrame | Series[Any], how: MergeHow = "inner", on: Label)

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [181]:
#merge = join
pd.merge(df1, df2 , how = 'outer', on = 'ID')

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   2    B   77.0
3   3    C    NaN
4   4  NaN   79.0

In [180]:
#merge = join
pd.merge(df1, df2 , how = 'left', on = 'ID')

# SYNTAX=    (left: DataFrame | Series[Any], right: DataFrame | Series[Any], how: MergeHow = "inner", on: Label)

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   2    B   77.0
3   3    C    NaN

In [187]:
#merge = join
pd.merge(df1, df2 , how = 'right', on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77
3   4  NaN     79

In [189]:
pd.merge(df1,df2,how ='inner', left_on ='ID', right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77