In [1]:
#Install pandas

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import pandas
import pandas as pd

In [4]:
pd.__version__

'3.0.0'

# Dataframe

In [5]:
 # 1. Create dataframe
df = pd.DataFrame([11,22,33], columns=['col_Name'])
print(df) # by default start by 0

   col_Name
0        11
1        22
2        33

In [6]:
print(type(df))

<class 'pandas.DataFrame'>

In [7]:
data = {
    
    'Name': ['madhav','vishakha','lalita','rishabh'],
    'Age' : [16,17,18,19],
    'Salary' : [6000,8000,9000,10000]
}

In [8]:
df = pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000
<class 'pandas.DataFrame'>

## More understanding on Dataframe

In [9]:
df.head() # print top rows

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000

In [10]:
df.head(2) # print 2 top rows

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000

In [11]:
df.tail()  # print bottom rows

       Name  Age  Salary
0    madhav   16    6000
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000

In [12]:
df.tail(3) # print bottom 3 rows

       Name  Age  Salary
1  vishakha   17    8000
2    lalita   18    9000
3   rishabh   19   10000

In [13]:
df.shape

(4, 3)

In [14]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [15]:
df.rename(columns={'Salary' :'Monthly_salary'}, inplace = True)  #changed in same dataframe

# or use df1 = df.rename(columns={'Salary' : 'Monthly_salary'})

In [16]:
df

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000
3   rishabh   19           10000

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [18]:
df.describe() # give statisistic summary about numerical type columns

             Age  Monthly_salary
count   4.000000        4.000000
mean   17.500000     8250.000000
std     1.290994     1707.825128
min    16.000000     6000.000000
25%    16.750000     7500.000000
50%    17.500000     8500.000000
75%    18.250000     9250.000000
max    19.000000    10000.000000

## SAVE AND LOAD DATA FROM CSV

In [19]:
df.to_csv('Test_data.csv', index = False)   # here df = name of dataframe 
# export dataframe

In [20]:
load_df = pd.read_csv('Test_data.csv') # function to load dataframe
#import dataframe
load_df                 # i incremented rishab's salary in excel

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000
3   rishabh   19           10000

# Rows and Columns Selection

In [21]:
df          # whole table of data

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000
3   rishabh   19           10000

In [22]:
# COLUMN SELECTION
df[['Name']]            # single column

       Name
0    madhav
1  vishakha
2    lalita
3   rishabh

In [23]:
df[['Name', 'Monthly_salary']]          # multi column

       Name  Monthly_salary
0    madhav            6000
1  vishakha            8000
2    lalita            9000
3   rishabh           10000

# Selecting row

In [24]:
# loc - index name based
df.loc[df.Name =='Madhav']
df.loc[(df.Name == 'Madhav') & (df.Monthly_salary>=5000)]

Empty DataFrame
Columns: [Name, Age, Monthly_salary]
Index: []

In [25]:
# iloc - index value based
df.iloc[0]     # gave me everything that was on index 0

Name              madhav
Age                   16
Monthly_salary      6000
Name: 0, dtype: object

In [26]:
df.iloc[0:2] # will work till (n-1)

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000

In [27]:
df.loc[0:2]   #  loc will include 2 as well

       Name  Age  Monthly_salary
0    madhav   16            6000
1  vishakha   17            8000
2    lalita   18            9000

# Filter Dataframe

In [28]:
df['Age'] > 15

0    True
1    True
2    True
3    True
Name: Age, dtype: bool

In [29]:
df['Age']>= 18

0    False
1    False
2     True
3     True
Name: Age, dtype: bool

In [30]:
df[df['Age'] >= 18]   # to filter out only true values

      Name  Age  Monthly_salary
2   lalita   18            9000
3  rishabh   19           10000

In [31]:
df_age_filter = df[df['Age'] >= 18]
df_age_filter

      Name  Age  Monthly_salary
2   lalita   18            9000
3  rishabh   19           10000

In [32]:
# filtering on the basis of 2 parameters
df[(df['Age'] >= 18) & (df['Monthly_salary'] >= 10000)]

      Name  Age  Monthly_salary
3  rishabh   19           10000

In [33]:
df.where(df['Age'] >= 18)     # keeps no. of rows and columns same

      Name   Age  Monthly_salary
0      NaN   NaN             NaN
1      NaN   NaN             NaN
2   lalita  18.0          9000.0
3  rishabh  19.0         10000.0

In [34]:
df.where(df['Age'] >= 18 , other = 'Not Eligible')

           Name           Age Monthly_salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        lalita            18           9000
3       rishabh            19          10000

## Operations On Rows And Columns( add , update, delete)

In [35]:
# Add new column
df['Team'] = ['CEO' , 'HR' , 'CTO' , 'DA']
df

       Name  Age  Monthly_salary Team
0    madhav   16            6000  CEO
1  vishakha   17            8000   HR
2    lalita   18            9000  CTO
3   rishabh   19           10000   DA

In [36]:
df['Bonus'] = df['Monthly_salary']*0.4
df       #performed operation and added new column

       Name  Age  Monthly_salary Team   Bonus
0    madhav   16            6000  CEO  2400.0
1  vishakha   17            8000   HR  3200.0
2    lalita   18            9000  CTO  3600.0
3   rishabh   19           10000   DA  4000.0

In [37]:
# Adding new row
df.loc[len(df)] =['sam' , 22 , 5500, ' EMPLOYEE' , 2000]  # this method will create a new row with this data as many times as you run this cell.
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17            8000         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

In [38]:
# deleting duplicates
df = df.drop_duplicates()
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17            8000         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

In [39]:
df = df.iloc[:5]
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17            8000         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

In [40]:
len(df)

5

# Update value

In [41]:
df.loc[1,'Monthly_salary'] = 9500
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17            9500         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

In [42]:
# Update value using column name

df.loc[df.Name == 'vishakha', 'Monthly_salary'] = 11000
df

       Name  Age  Monthly_salary       Team   Bonus
0    madhav   16            6000        CEO  2400.0
1  vishakha   17           11000         HR  3200.0
2    lalita   18            9000        CTO  3600.0
3   rishabh   19           10000         DA  4000.0
4       sam   22            5500   EMPLOYEE  2000.0

#Deleting value - row and column values

In [43]:
df = df.drop(df[df.Name == 'lalita'].index)   # drops row by default if not specified
# 0 --> row   ,   1 --> column

In [44]:
df[df.Name == 'lalita']

Empty DataFrame
Columns: [Name, Age, Monthly_salary, Team, Bonus]
Index: []

In [45]:
df.drop(1,axis =0) # index name

      Name  Age  Monthly_salary       Team   Bonus
0   madhav   16            6000        CEO  2400.0
3  rishabh   19           10000         DA  4000.0
4      sam   22            5500   EMPLOYEE  2000.0

In [46]:
# Deleting column
df.drop('Bonus', axis =1, inplace= True)

In [47]:
df

       Name  Age  Monthly_salary       Team
0    madhav   16            6000        CEO
1  vishakha   17           11000         HR
3   rishabh   19           10000         DA
4       sam   22            5500   EMPLOYEE

In [48]:
#df =df.drop(['Age','Team'],axis = 1)   # deleting multiple column
df

       Name  Age  Monthly_salary       Team
0    madhav   16            6000        CEO
1  vishakha   17           11000         HR
3   rishabh   19           10000         DA
4       sam   22            5500   EMPLOYEE

In [49]:
df

       Name  Age  Monthly_salary       Team
0    madhav   16            6000        CEO
1  vishakha   17           11000         HR
3   rishabh   19           10000         DA
4       sam   22            5500   EMPLOYEE

## Sort Values

In [50]:
df.sort_values('Monthly_salary')   # ascending order by default

       Name  Age  Monthly_salary       Team
4       sam   22            5500   EMPLOYEE
0    madhav   16            6000        CEO
3   rishabh   19           10000         DA
1  vishakha   17           11000         HR

In [51]:
df.sort_values('Monthly_salary', ascending = False)   #descending order

       Name  Age  Monthly_salary       Team
1  vishakha   17           11000         HR
3   rishabh   19           10000         DA
0    madhav   16            6000        CEO
4       sam   22            5500   EMPLOYEE

## Working with date value

In [52]:
df['DOJ'] = ['2024-01-01','2024-01-15','2024-03-28','2024-03-03']
df

       Name  Age  Monthly_salary       Team         DOJ
0    madhav   16            6000        CEO  2024-01-01
1  vishakha   17           11000         HR  2024-01-15
3   rishabh   19           10000         DA  2024-03-28
4       sam   22            5500   EMPLOYEE  2024-03-03

In [53]:
df['DOJ'].dtype

In [54]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [55]:
df['DOJ'].dtype   # rep datatime64[ns] data type in pandas

dtype('<M8[us]')

In [56]:
df1 = df

In [57]:
df1['DOJ2'] = ['01-01-2025','15-01-2025','28-03-2025','03-03-2025']
df1

       Name  Age  Monthly_salary       Team        DOJ        DOJ2
0    madhav   16            6000        CEO 2024-01-01  01-01-2025
1  vishakha   17           11000         HR 2024-01-15  15-01-2025
3   rishabh   19           10000         DA 2024-03-28  28-03-2025
4       sam   22            5500   EMPLOYEE 2024-03-03  03-03-2025

In [58]:
df1['DOJ2'].dtype

In [60]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format ='%d-%m-%Y')
df1['DOJ2'].dtype

dtype('<M8[us]')

In [61]:
df = df.drop('DOJ2', axis = 1)
df

       Name  Age  Monthly_salary       Team        DOJ
0    madhav   16            6000        CEO 2024-01-01
1  vishakha   17           11000         HR 2024-01-15
3   rishabh   19           10000         DA 2024-03-28
4       sam   22            5500   EMPLOYEE 2024-03-03

In [62]:
   # Extract year, month, week ,day
df['DOJ'].dt.year

0    2024
1    2024
3    2024
4    2024
Name: DOJ, dtype: int32

In [63]:
df['DOJ'].dt.month

0    1
1    1
3    3
4    3
Name: DOJ, dtype: int32

In [64]:
df['DOJ'].dt.day_name()

0      Monday
1      Monday
3    Thursday
4      Sunday
Name: DOJ, dtype: str

In [ ]:
df['month'] = df['DOJ'].dt.month
df   # saved the extracted month data into a new month column in df

       Name  Age  Monthly_salary       Team        DOJ  month
0    madhav   16            6000        CEO 2024-01-01      1
1  vishakha   17           11000         HR 2024-01-15      1
3   rishabh   19           10000         DA 2024-03-28      3
4       sam   22            5500   EMPLOYEE 2024-03-03      3

In [ ]:
df['DOJ'] + pd.Timedelta(days = 90)

0   2024-03-31
1   2024-04-14
3   2024-06-26
4   2024-06-01
Name: DOJ, dtype: datetime64[us]